KEYWORDS_SIN_TOOLS = {
    "adios",
    "adiós",
    "bien",
    "buenas",
    "buenas noches",
    "buenas tardes",
    "buenos dias",
    "buenos días",
    "bye",
    "chao",
    "hola",
    "como andas",
    "como esta",
    "como estas",
    "cómo andas",
    "cómo está",
    "cómo estás",
    "como te encuentras",
    "cómo te encuentra",
    "cómo te encuentras",
    "de acuerdo",
    "detente",
    "entendido",
    "estoy bien",
    "gracias",
    "hasta luego",
    "mal",
    "mas o menos",
    "más o menos",
    "nos vemos",
    "ok",
    "okay",
    "perfecto",
    "que tal",
    "qué tal",
    "quieto",
    "todo bien",
}

KEYWORDS_CON_TOOLS = {
    "abre ",
    "abre el archivo",
    "aleatorio",
    "anterior",
    "apaga",
    "apagar",
    "atras",
    "atrás",
    "baja el",
    "bloquea",
    "bloquear",
    "borra tu memoria",
    "busca",
    "buscar",
    "buenos dias",
    "buenos días",
    "cancela",
    "cancelar",
    "cancion",
    "canción",
    "canción anterior",
    "captura",
    "chiste",
    "cierra el proceso",
    "clic",
    "click",
    "clima",
    "consume",
    "continuar",
    "cuando sale",
    "cuándo sale",
    "cuanto cuesta",
    "cuánto cuesta",
    "cuanto vale",
    "cuánto vale",
    "cuesta",
    "detener",
    "detén",
    "dime qué",
    "encender",
    "escribe en",
    "frase",
    "google",
    "haz click",
    "hiberna",
    "hibernar",
    "horario",
    "internet",
    "lee ",
    "lee el archivo",
    "lee mi",
    "mata el proceso",
    "mezcla",
    "mezclar",
    "modo gaming",
    "modo no molestar",
    "modo trabajo",
    "motiv",
    "musica",
    "música",
    "mute",
    "navega a",
    "navegador",
    "next",
    "no molestar",
    "notepad",
    "noticias",
    "pagina",
    "página",
    "pausa",
    "pausar",
    "play",
    "pon ",
    "precio",
    "prender",
    "prev",
    "procesos",
    "reanuda",
    "recordatorio",
    "recuérdame",
    "reinicia",
    "reiniciar",
    "reproduce",
    "resetea",
    "resume",
    "rutina",
    "screenshot",
    "selector",
    "shuffle",
    "siguiente",
    "siguiente canción",
    "silencia",
    "silenciar",
    "sitio web",
    "spotify",
    "sube el",
    "temperatura",
    "url",
    "vale",
    "ve a ",
    "video",
    "volumen",
    "youtube",
}

KEYWORDS_WEB_DINAMICAS = {
    "actual",
    "clima",
    "cotiza",
    "cotizacion",
    "cual es",
    "cuál es",
    "cuando es",
    "cuando sale",
    "cuanto cuesta",
    "cuanto vale",
    "cuesta",
    "custa",
    "donde",
    "dónde",
    "estreno",
    "hoy",
    "lanzamiento",
    "marcador",
    "noticia",
    "noticias",
    "partido",
    "precio",
    "pronostico",
    "que es",
    "qué es",
    "que paso",
    "qué pasó",
    "quien",
    "quién",
    "quien es",
    "reciente",
    "resultado",
    "temperatura",
    "ultima",
    "última",
    "vale",
    "valor",
}
