"""Diccionario por defecto de pronunciación TTS (Piper)."""

TTS_PRONUN_DEFAULT = {
    "rg": "erre ge",
    "J.A.R.V.I.S": "YARBIS",
    "yarvis": "jarvis",
    "Yarvis": "Jarvis",
    "hack": "jac",
    "hacks": "jacs",
    "hackear": "jaquear",
    "hackeando": "jaqueando",
    "hackeado": "jaqueado",
    "hackeada": "jaqueada",
    "hackeados": "jaqueados",
    "hackeadas": "jaqueadas",
    "hackeo": "jaqueo",
    "hackeos": "jaqueos",
    "hacker": "jáquer",
    "hackers": "jáquers",
    "hacking": "jáquin",
    "hashtag": "jashtag",
    "hashtags": "jashtags",
    "hardware": "járdwer",
    "hardwares": "járdwers",
    "hotspot": "jótspot",
    "host": "jost",
    "hostname": "jóstneim",
    "hostnames": "jóstneims",
    "hosting": "jóstin",
    "hub": "jab",
    "hash": "jash",
    "hashes": "jashes",
    "html": "eich ti em ele",
    "hls": "eich ele ese",
    "http2": "eich ti ti pi dos",
    "http": "eich ti ti pi",
    "https": "eich ti ti pi ese",
    "hypervisor": "jaipervísor",
    "heurística": "eurística",
    "heuristicas": "eurísticas",
    "jailbreak": "yéilbreik",
    "jailbreaks": "yéilbreiks",
    "jailbreakear": "yéilbreikear",
    "jailbreakeo": "yéilbreikeo",
    "github": "guítjab",
    "gitlab": "guítlab",
    "git": "guít",
    "javascript": "yávascript",
    "java": "yáva",
    "json": "yéison",
    "jwt": "jota doble u te",
    "joystick": "yóstik",
    "joysticks": "yóstiks",
    "junior": "yunior",
    "jira": "yira",
    "jenkins": "yénkins",
    "jupyter": "yúpiter",
    "jquery": "yikueri",
    "jvm": "yei vi em",
    "jsx": "yei ese equis",
    "jsonrpc": "yéison ar pi si",
    "jar": "yar",
    "docker": "dóquer",
    "kubernetes": "kubernétis",
    "linux": "linuks",
    "windows": "guíndous",
    "wifi": "guaifai",
    "wi-fi": "guaifai",
    "router": "rúter",
    "firewall": "fáirguol",
    "firmware": "férmuer",
    "software": "sófuer",
    "malware": "málguer",
    "ransomware": "ránsomguer",
    "spyware": "spáiguer",
    "adware": "ádguer",
    "trojan": "tróyan",
    "exploit": "eksplóit",
    "exploits": "eksplóits",
    "payload": "péilod",
    "shellcode": "shélcod",
    "rootkit": "rutkit",
    "phishing": "físhin",
    "spoofing": "spúfin",
    "sniffer": "snífer",
    "botnet": "bótnet",
    "backend": "báckend",
    "frontend": "fróntend",
    "fullstack": "fulstak",
    "pipeline": "páiplain",
    "deploy": "diplói",
    "rollback": "rólbak",
    "debug": "dibág",
    "debuggear": "dibaguear",
    "bug": "bag",
    "bugs": "bags",
    "cache": "kash",
    "cracker": "cráquer",
    "crackers": "cráquers",
    "cloud": "claud",
    "server": "sérver",
    "servers": "sérvers",
    "cluster": "cláster",
    "endpoint": "éndpoint",
    "playstation": "pleisteishon",
    "play station": "plei steishon",
    "ps5": "pe ese cinco",
    "xbox": "eksboks",
    "jarvis": "yarvis",
    "spotify": "spótifai",
    "youtube": "yutúb",
    "twitch": "tuich",
    "discord": "díscord",
    "telegram": "télegram",
    "chatgpt": "chat yi pi ti",
    "openai": "ópen ei ai",
    "groq": "grók",
    "api": "a pe i",
    "ssh": "ese ese hache",
    "sdk": "ese de ka",
    "oauth": "ó auth",
    "token": "tóken",
    "refresh": "rifrésh",
    "prompt": "prómpt",
    "latency": "léitensi",
    "streaming": "strímin",
    "podcast": "pódcast",
    "backup": "báckup",
    "briefing": "brífin",
}
